project:
  type: website
  output-dir: docs

website:
  title: "Actuarial Daily"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/zrluety
      - icon: twitter-x
        href: https://x.com/zrluety
format:
  html:
    theme: cosmo
    css: styles.css



